language: python
sudo: required

jdk:
  - oraclejdk8
  - openjdk8

python:
   - "2.7"
   - "3.4"
   - "3.5"
   - "3.6"
   - "3.7"
   - "3.8"

install:
   - pip install coveralls
   - pip install flake8

script:
  - flake8 pyreportjasper/
  - chmod +x /home/travis/build/PyReportJasper/pyreportjasper/pyreportjasper/jasperstarter/bin/jasperstarter
  - coverage run setup.py test

after_success:
  - coveralls
